-- UTF-8 without BOM
-- This file is generated by genbeans tool. Do NOT edit it!
return require "util".initbeans {
	TestBean = { __type = 1, __vars = {
		[ 1] = { name = "value1", type = "number" },
		[ 2] = { name = "value2", type = "number" },
	}},
	TestKeyBean = { __type = 2, __vars = {
		[ 1] = { name = "key1", type = "number" },
		[ 2] = { name = "key2", type = "string" },
	}},
	TestType = { __type = 3, __vars = {
		[ 1] = { name = "v1", type = "boolean" },
		[ 2] = { name = "v2", type = "number" },
		[ 3] = { name = "v3", type = "number" },
		[ 4] = { name = "v4", type = "number" },
		[ 5] = { name = "v5", type = "number" },
		[ 6] = { name = "v6", type = "number" },
		[ 7] = { name = "v7", type = "number" },
		[ 8] = { name = "v8", type = "string" },
		[ 9] = { name = "v9", type = "string" },
		[10] = { name = "v10", type = "table", value = "boolean" },
		[11] = { name = "v11", type = "table", value = "number" },
		[12] = { name = "v12", type = "table", value = "number" },
		[13] = { name = "v13", type = "table", value = "number" },
		[14] = { name = "v14", type = "table", value = "number" },
		[15] = { name = "v15", type = "table", value = "number" },
		[16] = { name = "v16", type = "table", key = "number", value = "string" },
		[17] = { name = "v17", type = "table", key = "TestBean", value = "boolean" },
		[18] = { name = "v18", type = "table", key = "string", value = "TestBean" },
		[19] = { name = "v19", type = "TestBean" },
	}},
	TestEmpty = { __type = 4, __vars = {
	}},
}
