// This file is generated by genbeans tool. Do NOT edit it!
using System.Collections.Generic;

namespace jane.bean
{
	/** 全部beans的注册(自动生成的静态类) */
	public sealed class AllBeans
	{
		private AllBeans() {}

		/** 注册全部的beans到网络管理器. 必须在网络连接之前调用 */
		public static ICollection<Bean> getAllBeans()
		{
			ICollection<Bean> r = new List<Bean>(4);
			r.Add(new TestBean());
			r.Add(new TestKeyBean());
			r.Add(new TestType());
			r.Add(new TestEmpty());
			return r;
		}

		public static Dictionary<int, BeanHandler> getTestServerHandlers()
		{
			Dictionary<int, BeanHandler> r = new Dictionary<int, BeanHandler>(3 * 4);
			r.Add(1, new jane.handler.testserver.TestBeanHandler());
			r.Add(3, new jane.handler.testserver.TestTypeHandler());
			r.Add(4, new jane.handler.testserver.TestEmptyHandler());
			return r;
		}

		public static Dictionary<int, BeanHandler> getTestClientHandlers()
		{
			Dictionary<int, BeanHandler> r = new Dictionary<int, BeanHandler>(3 * 4);
			r.Add(1, new jane.handler.testclient.TestBeanHandler());
			r.Add(3, new jane.handler.testclient.TestTypeHandler());
			r.Add(4, new jane.handler.testclient.TestEmptyHandler());
			return r;
		}
	}
}
