// This file is generated by genbeans tool. Do NOT edit it!
using System.Collections.Generic;

namespace jane.bean
{
	/** 全部bean集合(自动生成的静态类) */
	public static class AllBeans
	{
		/** 获取全部的bean实例 */
		public static ICollection<Bean> getAllBeans()
		{
			List<Bean> r = new List<Bean>(4);
			r.Add(new TestBean());
			r.Add(new TestKeyBean());
			r.Add(new TestType());
			r.Add(new TestEmpty());
			return r;
		}

		public static IDictionary<int, BeanHandler> getTestServerHandlers()
		{
			Dictionary<int, BeanHandler> r = new Dictionary<int, BeanHandler>(3 * 4);
			r.Add(1, new jane.handler.testserver.TestBeanHandler());
			r.Add(3, new jane.handler.testserver.TestTypeHandler());
			r.Add(4, new jane.handler.testserver.TestEmptyHandler());
			return r;
		}

		public static IDictionary<int, BeanHandler> getTestClientHandlers()
		{
			Dictionary<int, BeanHandler> r = new Dictionary<int, BeanHandler>(3 * 4);
			r.Add(1, new jane.handler.testclient.TestBeanHandler());
			r.Add(3, new jane.handler.testclient.TestTypeHandler());
			r.Add(4, new jane.handler.testclient.TestEmptyHandler());
			return r;
		}
	}
}
