// This file is generated by genbeans tool. Do NOT edit it!
using System.Collections.Generic;

namespace Jane.Bean
{
	/** 全部bean集合(自动生成的静态类) */
	public class AllBeans
	{
		/** 获取全部bean的创建代理 */
		public static IDictionary<int, NetManager.BeanDelegate> GetAllBeans()
		{
			IDictionary<int, NetManager.BeanDelegate> r = new Dictionary<int, NetManager.BeanDelegate>(3 * 4);
			r.Add(1, TestBean.CreateIBean);
			r.Add(2, TestType.CreateIBean);
			r.Add(3, TestEmpty.CreateIBean);
			return r;
		}

		public static IDictionary<int, NetManager.HandlerDelegate> GetTestClientHandlers()
		{
			IDictionary<int, NetManager.HandlerDelegate> r = new Dictionary<int, NetManager.HandlerDelegate>(2 * 4);
			r.Add(1, Jane.Handler.TestBeanHandler.OnProcess);
			r.Add(2, Jane.Handler.TestTypeHandler.OnProcess);
			return r;
		}
	}
}
