// This file is generated by genbeans tool. Do NOT edit it!
using System.Collections.Generic;

namespace Jane.Bean
{
	/** 全部bean集合(自动生成的静态类) */
	public struct AllBeans
	{
		/** 获取全部bean的创建代理 */
		public static IDictionary<int, NetManager.BeanDelegate> getAllBeans()
		{
			IDictionary<int, NetManager.BeanDelegate> r = new Dictionary<int, NetManager.BeanDelegate>(3 * 4);
			r.Add(1, TestBean.create);
			r.Add(2, TestType.create);
			r.Add(3, TestEmpty.create);
			return r;
		}

		public static IDictionary<int, NetManager.HandlerDelegate> getTestClientHandlers()
		{
			IDictionary<int, NetManager.HandlerDelegate> r = new Dictionary<int, NetManager.HandlerDelegate>(2 * 4);
			r.Add(1, Jane.Handler.TestBeanHandler.onProcess);
			r.Add(2, Jane.Handler.TestTypeHandler.onProcess);
			return r;
		}
	}
}
