// This file is generated by genbeans tool. Do NOT edit it! @formatter:off
package jane.bean;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jane.core.Bean;
import jane.core.BeanHandler;
import jane.core.map.IntHashMap;

/** 全部beans的注册(自动生成的静态类) */
public final class AllBeans
{
	private AllBeans() {}

	/** 获取全部的bean实例 */
	public static Collection<Bean<?>> getAllBeans()
	{
		List<Bean<?>> r = new ArrayList<>(3);
		r.add(TestBean.BEAN_STUB);
		r.add(TestType.BEAN_STUB);
		r.add(TestEmpty.BEAN_STUB);
		return r;
	}

	public static IntHashMap<BeanHandler<?>> getTestClientHandlers()
	{
		return getTestClientHandlers(null);
	}

	public static IntHashMap<BeanHandler<?>> getTestClientHandlers(IntHashMap<BeanHandler<?>> r)
	{
		if(r == null) r = new IntHashMap<>(2 * 4);
		r.put(1, new jane.handler.testclient.TestBeanHandler());
		r.put(2, new jane.handler.testclient.TestTypeHandler());
		return r;
	}

	public static IntHashMap<BeanHandler<?>> getTestServerHandlers()
	{
		return getTestServerHandlers(null);
	}

	public static IntHashMap<BeanHandler<?>> getTestServerHandlers(IntHashMap<BeanHandler<?>> r)
	{
		if(r == null) r = new IntHashMap<>(3 * 4);
		r.put(1, new jane.handler.testserver.TestBeanHandler());
		r.put(2, new jane.handler.testserver.TestTypeHandler());
		r.put(3, new jane.handler.testserver.TestEmptyHandler());
		return r;
	}
}
