// This file is generated by genbeans tool. Do NOT edit it! @formatter:off
package jane.bean;

import jane.core.RpcBean;

public final class TestRpcBean2 extends RpcBean<TestBean, TestBean>
{
	private static final long serialVersionUID = 0xbeac3a46ee8864faL;
	public  static final TestRpcBean2 BEAN_STUB = new TestRpcBean2();
	public TestRpcBean2() {}
	public TestRpcBean2(TestBean a) { arg = a; }
	@Override public int type() { return 6; }
	@Override public TestRpcBean2 stub() { return BEAN_STUB; }
	@Override public TestRpcBean2 create() { return new TestRpcBean2(); }
	@Override public TestBean createArg() { return new TestBean(); }
	@Override public TestBean createRes() { return new TestBean(); }
}
